Login UI
Milahn-Henri-Louis-Irwin-ITBSA/tripwiz-ui pull request #5
Opened 2023-10-22 14:09 UTC by HenriLouw

I accidentally created the feed on the login branch... So you guys can get a 2 for 1 special when reviewing XD. I'm not done with the feed yet; I just want to get it out so long that I don't block Milahn. I will probably finish the rest tonight. As requested yesterday, I'll fix my commit names going forward...

2023-10-22 15:31 UTC, milahnmartin requested changes
Everything looks good, just the inconsistency with the import annotations please. :)

2023-10-22 18:16 UTC, HenriLouw commented on src/views/Map.jsx
>  import Sidebar from '../components/Sidebar';
I did not create this... But I will fix it for you :)

2023-10-22 18:16 UTC, HenriLouw commented on src/components/ui/button.jsx
> +import { cn } from '../utils';
I did not create this... But I will fix it for you :)

2023-10-22 18:19 UTC, milahnmartin commented on src/views/Map.jsx
>  import Sidebar from '../components/Sidebar';
my bad, no idea why I did that, the people who reviewed didnt pick it up I guess :()

2023-10-23 13:18 UTC, Louis-Bat17 commented
After el reviews, tis looking lit, thanks Henri!

2023-10-23 13:19 UTC, milahnmartin approved these changes
Looks good thank you !

2023-10-23 13:26 UTC, Louis-Bat17 approved these changes

2023-10-23 17:39 UTC, merged